import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Input, Box, Stack, Divider } from "@mui/material";
import FormControl from "@mui/material/FormControl";
import Button, { ButtonProps } from "@mui/material/Button";
import GitHubIcon from "@mui/icons-material/GitHub";
import GoogleIcon from "@mui/icons-material/Google";
import { alpha, styled } from "@mui/material/styles";
import Typography from "@mui/material/Typography";
import { InputProps } from "@mui/material/Input";
import TextField, { TextFieldProps } from "@mui/material/TextField";
import { borderRadius } from "@mui/system";

const inter = Inter({ subsets: ["latin"] });

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            alignContent: "center",
            width: "100%",
            height: "100vh",
          }}
        >
          <Stack
            spacing={2}
            sx={{
              width: "350px",
            }}
          >
            <Divider>
              <Typography sx={{ fontSize: 14 }}>SIGN IN</Typography>
            </Divider>
            <LoginTextfield label="username" />
            <LoginTextfield label="password" />
            <LoginButton>Sign In</LoginButton>
            <Divider>
              <Typography sx={{ fontSize: 14 }}>OR SIGN IN WITH</Typography>
            </Divider>
            <LoginButton startIcon={<GoogleIcon fontSize="small" />}>
              Google
            </LoginButton>
            <LoginButton startIcon={<GitHubIcon fontSize="small" />}>
              Github
            </LoginButton>
          </Stack>
        </Box>
      </main>
    </>
  );
};

const LoginButton = styled((props) => (
  <Button variant="outlined" {...props} />
))<ButtonProps>(({ theme }) => ({
  borderRadius: "8px",
  width: "100%",
  height: 40,
  textTransform: "none",
  fontWeight: "bold",
}));

const LoginTextfield = styled((props) => (
  <TextField
    size="small"
    inputProps={{
      sx: {
        borderRadius: "8px !important",
      },
    }}
    {...props}
  />
))<TextFieldProps>(({ theme }) => ({}));

export default Home;
