import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { Box, Stack, Divider } from "@mui/material";
import GitHubIcon from "@mui/icons-material/GitHub";
import GoogleIcon from "@mui/icons-material/Google";
import { styled } from "@mui/material/styles";
import Typography from "@mui/material/Typography";
import TextField, { TextFieldProps } from "@mui/material/TextField";
import React from "react";
import InputAdornment from "@mui/material/InputAdornment";
import IconButton from "@mui/material/IconButton";
import { Visibility, VisibilityOff } from "@mui/icons-material";
import LoginButton from "@/component/common/button/LoginButton";

const inter = Inter({ subsets: ["latin"] });

const Home = () => {
  const [showPassword, setShowPassword] = React.useState(false);
  const handleClickShowPassword = () => setShowPassword((show) => !show);
  const handleMouseDownPassword = (
    event: React.MouseEvent<HTMLButtonElement>
  ) => {
    event.preventDefault();
  };

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            alignContent: "center",
            width: "100%",
            height: "100vh",
          }}
        >
          <Stack
            spacing={2}
            sx={{
              width: "350px",
            }}
          >
            <Typography variant="h2" component="h1">
              Login
            </Typography>
            <Divider>
              <Typography sx={{ fontSize: 14 }}>Sign In</Typography>
            </Divider>
            <LoginTextfield label="username" />
            <LoginTextfield
              id="password-input"
              type={showPassword ? "text" : "password"}
              label="password"
              autoComplete="current-password"
              InputProps={{
                endAdornment: (
                  <InputAdornment position="end">
                    <IconButton
                      aria-label="toggle password visibility"
                      onClick={handleClickShowPassword}
                      onMouseDown={handleMouseDownPassword}
                      edge="end"
                    >
                      {showPassword ? <VisibilityOff /> : <Visibility />}
                    </IconButton>
                  </InputAdornment>
                ),
              }}
            />
            <LoginButton>Sign In</LoginButton>
            <Divider>
              <Typography sx={{ fontSize: 14 }}>or Sign In with</Typography>
            </Divider>
            <LoginButton startIcon={<GoogleIcon fontSize="small" />}>
              <Typography>Google</Typography>
            </LoginButton>
            <LoginButton
              startIcon={<GitHubIcon fontSize="small" />}
              sx={{ backgroundColor: "black" }}
            >
              <Typography>GitHub</Typography>
            </LoginButton>
          </Stack>
        </Box>
      </main>
    </>
  );
};

const LoginTextfield = styled((props) => (
  <TextField
    size="small"
    inputProps={{
      sx: {
        borderRadius: "8px !important",
      },
    }}
    {...props}
  />
))<TextFieldProps>(({ theme }) => ({}));

export default Home;
